name: career_sphere
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  encrypt_shared_preferences: ^0.8.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.0
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  local_auth: ^2.3.0
  meta: ^1.15.0
  shared_preferences: ^2.3.4
  socket_io_client: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_generator: ^0.4.1

flutter_icons:
  image_path: assets/logo.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
