// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1CLAdruvdJzcDPX3o46dWcNIhtSs5Hk',
    appId: '1:747989124796:android:ae5f20b10f613dd9bf72b9',
    messagingSenderId: '747989124796',
    projectId: 'liveprojects-2111d',
    databaseURL: 'https://liveprojects-2111d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liveprojects-2111d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWREjnXb7USF24dXHwOoW1fRDMxo1UnkI',
    appId: '1:747989124796:ios:250e3eeddc76fb1cbf72b9',
    messagingSenderId: '747989124796',
    projectId: 'liveprojects-2111d',
    databaseURL: 'https://liveprojects-2111d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liveprojects-2111d.appspot.com',
    androidClientId: '747989124796-5c37i58nffgqomrak4c44ap78295pdbt.apps.googleusercontent.com',
    iosClientId: '747989124796-b18qune7m0bjh25is4aefchpa9u20eu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerSphere',
  );
}
